remove extra-deps, add cabal file
serokell/co-log-sys pull request #2
Opened 2018-11-21 09:37 UTC by pasqu4le

**Description:**

This update removes both stack extra-deps: 
- `co-log-core` is now taken from Hackage instead of pulling it from git
- `loot-prelude` is not used anymore (but `universum` still is)

With this done we can have a working `cabal` file and so support `build` and `new-build`, solving issue #1 

Note: this also bumps up the version number so it can be downloaded with this fix from Hackage from now on

**Checklist:**

- [x] Updated docs if necessary
- [x] My code complies with the [style guide](docs/code-style.md)
- [x] Tested my changes if they modify code

2018-11-21 13:35 UTC, flyingleafe requested changes
I think that since we aim to support simple `cabal build`, it makes little sense to maintain both `package.yaml` and `co-log-sys.cabal`, especially given that we don't use any Yaml features for this project and therefore using `package.yaml gives us no apparent advantage over simple `.cabal` file.

2018-11-21 15:17 UTC, pasqu4le commented
@flyingleafe `package.yaml` has been removed

2018-11-21 18:07 UTC, flyingleafe approved these changes

2018-11-21 18:07 UTC, merged

2019-11-20 12:46 UTC, kirelagin commented
> using `package.yaml` gives us no apparent advantage

I dunno, I think pretty much anyone who looked at the generated cabal file would argue with this statement.